[package]
name = "codelldb2"
version = "0.1.0"
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]

[dependencies]
lldb = "0.0.7"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
debugserver-types = "0.4.0"
